language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
r_github_packages:
- cloudyr/aws.s3
after_failure:
  email:
    recipients:
    - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: WfWJviioeVh7udl33N+7MupHNR9TIQO+DY+MQ4khYPoXG2vAun5BBBB2XJjAdje6R7ZdblWAJ322v8wNfQ+Mt57floj+WlDejgBcahZrUXhH4fiVagprGnHMTLHM+hVYf2vyfwDW9Mpn101pYtvpPL/w2xso0D8m2e1FTWVwRH8=
